package com.campnav.backend.model;

public enum BubbleType {
    ROUNDED, SPEECH, THOUGHT, GLOW, NEON, COMIC, GLASS, CLOUD, PAINT_SPLASH, ANIME_POP, CYBER_PUNK, DREAMY, GOLDEN, ICY, FIRE, RAINBOW, HALLOWEEN, LOVE, GALAXY, AQUA, SUNSET, NEON_PULSE, GLASS_MORPH, BUBBLE_POP, STICKER, RIBBON, QUOTE, EMOTE_BUBBLE, MINIMALIST, DOTTED, WAVY, CRYSTAL, GLITCH, VINTAGE, PAPER_CUT, ORIGAMI, TYPED, HAND_DRAWN, WATERCOLOR, OIL_PAINT, SKETCH, CARTOON, RETRO
}
