package com.campnav.backend.model;

public enum ShapeType {
    RECTANGLE, CIRCLE, TRIANGLE, STAR, HEART, BLOB,
    DIAMOND, PENTAGON, HEXAGON, OCTAGON, CROSS, ARROW,
    INFINITY, CLOVER, MOON, SUN, CLOUD_SHAPE, LIGHTNING,
    FLOWER, LEAF, DROP, SPIRAL, GEAR, EXPLOSION
}
