spring.application.name=campnav-backend

# PostgreSQL Configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/campnav
# spring.datasource.username=postgres
# spring.datasource.password=password

# H2 Configuration (For development/testing)
spring.datasource.url=jdbc:h2:mem:campnavdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate/Flyway settings
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8081
